#pragma once

// ESC/POS Font B, as the 10 x 24 dot cell a thermal printer actually uses.
//
// ESC M 1 selects it: at 10 dots to the column 57 of them fit the 576 dot
// printable width of 80 mm paper at 203 dpi. The cell is as tall as Font A's
// and stands on the same baseline, so a line that mixes the two lines up. The
// table is generated by tools/genfont.py - edit that, not this file.

const int FONT_B_WIDTH = 10;
const int FONT_B_HEIGHT = 24;

// The 24 rows of `ch`, one 16-bit word each, bit 9 being the leftmost dot.
// Returns null for a character the table has no glyph for.
const unsigned short *FontBGlyph(wchar_t ch);
