#pragma once

// ESC/POS Font A, as the 12 x 24 dot cell a thermal printer actually uses.
//
// 48 columns of 12 dots is the 576 dot printable width of 80 mm paper at
// 203 dpi, so a receipt only lines up if the glyphs live on this grid. The
// table is generated by tools/genfont.py - edit that, not this file.

const int FONT_A_WIDTH = 12;
const int FONT_A_HEIGHT = 24;

// The 24 rows of `ch`, one 16-bit word each, bit 11 being the leftmost dot.
// Returns null for a character the table has no glyph for.
const unsigned short *FontAGlyph(wchar_t ch);
